"""Fix column names in ApplicationModel

Revision ID: 1f71cf9cb3a9
Revises: a87ae258065a
Create Date: 2025-09-07 12:14:07.620043

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f71cf9cb3a9'
down_revision: Union[str, None] = 'a87ae258065a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('team_name', sa.String(length=255), nullable=False))
    op.add_column('applications', sa.Column('team_participants_number', sa.Integer(), nullable=False))
    op.drop_column('applications', 'teamParticipantsNumber')
    op.drop_column('applications', 'teamName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('teamName', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('teamParticipantsNumber', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('applications', 'team_participants_number')
    op.drop_column('applications', 'team_name')
    # ### end Alembic commands ###
