"""Add requests table

Revision ID: bef7ac57bdac
Revises: 1f71cf9cb3a9
Create Date: 2025-09-10 15:23:33.138965

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef7ac57bdac'
down_revision: Union[str, None] = '1f71cf9cb3a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('CONSULTATION', 'PARTNERSHIP', 'EVENT_GAME_ORDER', name='type_request'), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'VIEWED', 'PROCESSED', name='status_request'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
